templates:
  scm-init: git
  params:
    author-name: Your Name
    author-email: you@example.com
    category: Experiment
    copyright: 'Copyright: (c) 2019 Your Name'
    github-username: your_github_name

default-template: "/home/nobsun/.stack/templates/your.hsfiles"
