templates:
  scm-init: git
  params:
    author-name: Nobuo Yamashita
    author-email: nobsun@gmail.com
    category: Experiment
    copyright: 'Copyright: (c) 2019 Nobuo Yamashita'
    github-username: nobsun

default-template: "/home/nobsun/.stack/ny.hsfiles"
